name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  http: ^1.2.1
  flutter_riverpod: ^3.0.3
  provider: ^6.1.2
  go_router: ^14.2.0
  carousel_slider: ^5.0.0
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  animate_icons: ^2.0.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/image.png
    - lib/assets/icons/star.png